method=ctm
matchTiles=betterglass:magenta_stained_clear_glass
matchBlocks=betterglass:magenta_stained_clear_glass
tiles=0-46
connect=block
resourceCondition=betterglass:textures/block/magenta_stained_clear_glass.png
