method=ctm
matchTiles=betterglass:white_stained_clear_glass
matchBlocks=betterglass:white_stained_clear_glass
tiles=0-46
connect=block
resourceCondition=betterglass:textures/block/white_stained_clear_glass.png
