method=ctm
matchTiles=betterglass:green_colored_scratched_glass
matchBlocks=betterglass:green_colored_scratched_glass
tiles=0-46
connect=block
resourceCondition=betterglass:textures/block/green_colored_scratched_glass.png
