method=ctm
matchTiles=betterglass:brown_stained_clear_glass
matchBlocks=betterglass:brown_stained_clear_glass
tiles=0-46
connect=block
resourceCondition=betterglass:textures/block/brown_stained_clear_glass.png
