method=ctm
matchTiles=betterglass:magenta_stained_500_downloads_chiseled_scratched_tinted_glass
matchBlocks=betterglass:magenta_stained_500_downloads_chiseled_scratched_tinted_glass_pane
tiles=0-46
connect=block
