method=ctm
matchTiles=betterglass:gray_colored_scratched_glass
matchBlocks=betterglass:gray_colored_scratched_glass
tiles=0-46
connect=block
resourceCondition=betterglass:textures/block/gray_colored_scratched_glass.png
