method=ctm
matchTiles=purple_colored_scratched_glass
matchBlocks=purple_colored_scratched_glass
tiles=0-46
connect=block
resourceCondition=betterglass:textures/block/purple_colored_scratched_glass.png
