method=ctm
matchTiles=light_gray_colored_clear_glass
matchBlocks=light_gray_colored_clear_glass
tiles=0-46
connect=block
resourceCondition=betterglass:textures/block/light_gray_colored_clear_glass.png
