method=ctm
matchTiles=betterglass:light_gray_stained_clear_glass
matchBlocks=betterglass:light_gray_stained_clear_glass
tiles=0-46
connect=block
resourceCondition=betterglass:textures/block/light_gray_stained_clear_glass.png
