method=ctm
matchTiles=betterglass:purple_stained_500_downloads_chiseled_clear_tinted_glass
matchBlocks=betterglass:purple_stained_500_downloads_chiseled_clear_tinted_glass_pane
tiles=0-46
connect=block
